# Set BOOKMARKS associate array
typeset -Ag BOOKMARKS=(
  [chezmoi]="~/.local/share/chezmoi"
  [notes-manager]="~/develop/notes-manager"
  [pigshare]="~/develop/pigshare"
  [pybib]="~/develop/pybib"
  [pydef]="~/develop/pyder"
  [sandbox]="~/develop/sandbox"
  [scripts]="~/develop/scripts"
  [www.vonwelch.com]="~/develop/www.vonwelch.com"
  [www.vwelch.com]="~/develop/www.vwelch.com"
  [contexts]="~/.hammerspoon/myspoons/contexts.spoon"
  [email]="~/.hammerspoon/myspoons/email.spoon"
  [modelext]="~/.hammerspoon/myspoons/modalext.spoon"
  [mousebind]="~/.hammerspoon/myspoons/mousebind.spoon"
  [pasteboardext]="~/.hammerspoon/myspoons/pasteboardext.spoon"
  [pasteregister]="~/.hammerspoon/myspoons/pasteregister.spoon"
  [pastestack]="~/.hammerspoon/myspoons/pastestack.spoon"
  [screensaver]="~/.hammerspoon/myspoons/screensaver.spoon"
  [tiler]="~/.hammerspoon/myspoons/tiler.spoon"
  [ww]="~/.hammerspoon/myspoons/watcherwatcher.spoon"
  [ytmusic]="~/.hammerspoon/myspoons/ytmusic.spoon"
  [private]="~/private"
  [tumxp-popup]="~/repos/tmuxp-popup"
  [to-env]="~/repos/to-env"
  [cd-utils]="~/develop/cd-utils"
  [dvd-utils]="~/develop/dvd-util"
  [bpp]="~/Google Drive/My Drive/BPP Board/"
  [constellation]="~/google drive/my drive/Constellation/"
  [beacon]="~/Google Drive/My Drive/Beacon/"
  [personal]="~/Google Drive/My Drive/Personal/"
  [resume]="~/Google Drive/My Drive/Resume/"
  [rotary]="~/Google Drive/My Drive/Rotary/"
  [wesnoth]="~/Google Drive/My Drive/Wesnoth/"
  )

